import Head from "next/head";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <Head>
        <title>タスク当番表</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        {/* <link
          href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=optional"
          rel="stylesheet"
        /> */}
      </Head>
      <body className="font-sans">{children}</body>
    </html>
  );
}
