import UrlCopyButton from "components/atoms/urlCopyButton";
import ResetButton from "components/atoms/resetButton";
import Head from "next/head";
import "./globals.css";
import React from "react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <Head>
        <title>タスク当番表</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <body className="font-sans">
        <header className="m-4 flex place-content-between border-b-2 p-2">
          <p className="stroke-4 text-xl font-bold antialiased drop-shadow-md">
            タスク当番くん
          </p>
          <div className="flex justify-between [&>*]:mr-4">
            <ResetButton></ResetButton>
            <UrlCopyButton></UrlCopyButton>
          </div>
        </header>
        <article>{children}</article>
        <footer className="absolute bottom-0">
          <aside>
            <pre>
              <small>(C) 2023 showyha08</small>
            </pre>
          </aside>
        </footer>
      </body>
    </html>
  );
}
